//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Class responsible for creatin test request and running rule testing
/// </summary>
public class RuleTesterManager
{
	public virtual object IEnumerable<TestRequest> testRequests
	{
		get;
		set;
	}

	public virtual object IRuleTester ruleTester
	{
		get;
		set;
	}

	public virtual IRuleTester IRuleTester
	{
		get;
		set;
	}

	public virtual void IEnumerable<TestRequest> GenerateTests(object DataSet[] testSets, object RuleSet ruleSet)
	{
		throw new System.NotImplementedException();
	}

	public virtual void IEnumerable<TestRequest> GenerateTestSeries(object RuleFilterAggregator filterAggregator, object DataSet[] testSets)
	{
		throw new System.NotImplementedException();
	}

	public virtual void IEnumerable<TestResult> RunTesting()
	{
		throw new System.NotImplementedException();
	}

	public virtual void void AddTestRequest(object TestRequest testRequest)
	{
		throw new System.NotImplementedException();
	}

	public virtual void void DeleteTestRequest(object int index)
	{
		throw new System.NotImplementedException();
	}

	public virtual void viod Clear()
	{
		throw new System.NotImplementedException();
	}

}

