//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestResult
{
	public virtual object ConfusionMatrix confusionMatrix
	{
		get;
		set;
	}

	public virtual object string[] decisionValues
	{
		get;
		set;
	}

	public virtual object TestRequest testRequest
	{
		get;
		set;
	}

	public virtual ConfusionMatrix ConfusionMatrix
	{
		get;
		set;
	}

	public virtual TestRequest TestRequest
	{
		get;
		set;
	}

}

