//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConfusionMatrix
{
    public virtual int TruePositives { get; set; }
    public virtual int TrueNegatives { get; set; }
    public virtual int FalseNegatives { get; set; }
    public virtual int FalsePositives { get; set; }
}

