//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RuleTester : IRuleTester
{
	public virtual void IEnumerable<TestResult> RunTesting(object IEnumerable<TestRequest>)
	{
		throw new System.NotImplementedException();
	}

}

