//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TestRequest
{
	public virtual object RuleSet ruleSet
	{
		get;
		set;
	}

	public virtual object DataSet testSet
	{
		get;
		set;
	}

	public virtual object ConflictResolvingMethod resolvingMethod
	{
		get;
		set;
	}

}

